### PR TITLE
Normalize composer

### PR DESCRIPTION
**Pull request by ghostwriter**
**[QA]**
* Normalize `composer.json` and/or update `composer.lock`
    - Restructure `composer.json` according to the underlying [JSON schema](https://getcomposer.org/schema.json).
    - Prevent inconsistencies between all (200+) repositories across all 3 GitHub organizations (`laminas`, `mezzio`, and `laminas-api-tools`).

### CODE REVIEW

**Review by michalbundyra — COMMENTED** [review]
I am not sure if it is needed. We tried to "normalize" composer.json during the migration from ZF and then we agreed consistent format. Order of the sections in the file does not matter for the file validity (and as I said it has been changed to that order during the migration).

**Comment by ghostwriter** [comment]
yes, I was made aware, my conversation with [froschdesign](https://github.com/laminas/laminas-json-server/issues/15#issuecomment-833738418) that is why i made a PR in each repo on all 3 organizations.

consistent **"Normalized"** format.

**Comment by froschdesign** [comment]
> yes, I was made aware, my conversation with [froschdesign](https://github.com/laminas/laminas-json-server/issues/15#issuecomment-833738418) that is why i made a PR in each repo on all 3 organizations.

But I never said that implementation was necessary or wanted. A previous discussion would have been helpful for all sides.

**Comment by ghostwriter** [comment]
> But I never said that implementation was necessary or wanted. A previous discussion would have been helpful for all sides.

Correct, i was only talking about the need for a "consistent format". (2 quotes below)

>> The problem is that inconsistencies arise between the repositories which can be result in more work or other problems. And with more than 180 repositories in 3 different GitHub organizations, nobody needs that.

>> We tried to "normalize" composer.json during the migration from ZF and then we agreed consistent format.

I may have misunderstood something. I thought i was fixing the inconsistencies issue that hindered this orgs from completing  this task during the initial migration from ZF, by adding the QA checks via laminas/laminas-continuous-integration-action#38 & laminas/laminas-ci-matrix-action#32 and sending each repo a PR with the necessary changes.

**Comment by weierophinney** [comment]
Please [open an RFC with the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/issues/new) before creating batched pull requests. This is requested so as to:

- Ensure no duplication of effort occurs.
- Ensure the changes have been discussed and approved by the TSC.
- Ensure there will be maintainers available to review and merge the patches.
- Ensure tooling automation is in place to prevent future regressions.

**Pull request closed without merging**
