### PR TITLE
PHP8.4 Support Added

### PR DESCRIPTION
**Pull request by cod43156**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by froschdesign** [comment]
@cod43156 
Please change the configuration for continuous integration to ignore version 8.4:

https://github.com/laminas/laminas-cli/blob/ab90e625bd9a0bd01889ffdf66d368cad0678892/.laminas-ci.json#L3

**Comment by cod43156** [comment]
> @cod43156 Please change the configuration for continuous integration to ignore version 8.4:
> 
> https://github.com/laminas/laminas-cli/blob/ab90e625bd9a0bd01889ffdf66d368cad0678892/.laminas-ci.json#L3

@froschdesign The configuration for continuous integration has been updated to ignore version 8.4

**Comment by nishant04412** [comment]
@froschdesign The ci failures are not related to this PR's changes and are coming in other PRs as well.

https://github.com/laminas/laminas-cli/actions/runs/11384095519/job/31671094663?pr=126

Can you please check and advise if we need to address the failures ?

**Comment by gsteel** [comment]
CI Failures will need to be fixed in a separate patch before other PRs can be merged

**Comment by gsteel** [comment]
Thanks @cod43156 - This was handled in #131

**Pull request closed without merging**
