### PR TITLE
Remove lazy loading functionality

### LINKED ISSUE #28: Issue with integrating symfony/messenger command
### Bug Report

The whole console application might fail completely when an exception is thrown in lazy command configure a part

|    Q        |   A
|------------ | ------
| Version(s)  | dev-master

#### Summary

It looks like the LazyLoadingCommand is having a part that might sometimes throw an exception because of not initialized dependencies of the underlying command.

For example:

```
    /**
     * {@inheritdoc}
     */
    protected function configure(): void
    {
        $defaultReceiverName = 1 === \count($this->receiverNames) ? current($this->receiverNames) : null;

        $this
            ->setDefinition([
                new InputArgument('receivers', InputArgument::IS_ARRAY, 'Names of the receivers/transports to consume in order of priority', $defaultReceiverName ? [$defaultReceiverName] : []),
                new InputOption('limit', 'l', InputOption::VALUE_REQUIRED, 'Limit the number of received messages'),
                new InputOption('memory-limit', 'm', InputOption::VALUE_REQUIRED, 'The memory limit the worker can consume'),
                new InputOption('time-limit', 't', InputOption::VALUE_REQUIRED, 'The time limit in seconds the worker can run'),
                new InputOption('sleep', null, InputOption::VALUE_REQUIRED, 'Seconds to sleep before asking for new messages after no messages were found', 1),
                new InputOption('bus', 'b', InputOption::VALUE_REQUIRED, 'Name of the bus to which received messages should be dispatched (if not passed, bus is determined automatically)'),
            ])
// the rest of the code
}
```

As a solution, we could catch any incoming errors being thrown by the configure method, because it might be a common scenario that some configuration steps are based on internal dependencies injected.

```
        // \Laminas\Cli\LazyLoadingCommand
        try{
            $command->configure();
        } catch (\Throwable $exception) {}
```

#### Current behavior

This code is throwing a warning exception because of empty receiverNames property, then the whole list is not displaying

#### How to reproduce

Connect Symfony messenger consume command to the app and run the CLI

#### Expected behavior

No error should be thrown and the list of available commands should be displayed.

### PR DESCRIPTION
**Pull request by weierophinney**
Per #28, the `configure()` method of a command is generally used to configure a command's metadata: the description, arguments, and options.  In some occasions, those operations require values passed as constructor arguments.

With the previous LazyLoadingCommand feature added in #12, this could lead to a few problems:

- Missing command metadata, which would lead to users not getting information required to consume the command correctly.
- Warnings interspersed with command information, generally due to misconfigured or missing information normally provided via the constructor.

This patch removes the lazy loading features. The primary rationale for them were to prevent scenarios where dependencies that performed expensive operations during instantiation or `configure()` would lead to slow command-line usage. These are likely going to be rare, and should be dealt with on a case-by-case basis by decorating the problematic commands — instead of _all_ commands.

Fixes #28.

### CODE REVIEW

**Comment by michalbundyra** [comment]
@weierophinney should we also add some test to cover #28?

**Comment by weierophinney** [comment]
> @weierophinney should we also add some test to cover #28?

No - because the root cause was in the constructor of `LazyLoadingCommand` (I'd actually written a test against that class previously), and now that functionality no longer exists. There's literally nothing to test now, because we are no longer introducing new behavior; we're reverting to the original symfony/console behavior.

**Comment by weierophinney** [comment]
As discussed on Slack, the purpose of such a test would be to raise an error during testing in the scenario somebody wants to re-add a similar feature. As such, I'll add the test in a bit.

**Comment by weierophinney** [comment]
@michalbundyra I've added tests showing that `list` and `help <command_name>` now expect that information created during `configure()` is present; these will help demonstrate issues should somebody decide to submit a patch later to decorate commands.

**Pull request merged**
