### PR TITLE
Update to latest PHP 8.1 syntax

### PR DESCRIPTION
**Pull request by samsonasik**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 8.1, php 8.1 syntax can be applied.

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to review 👍 , CI error on php 8.2 and 8.3 seems unrelated.

https://github.com/laminas/laminas-cli/actions/runs/11642048570/job/32421206364?pr=129#step:3:406

as happen on other PR as well, like in https://github.com/laminas/laminas-cli/pull/126

**Comment by fezfez** [comment]
@samsonasik see https://github.com/laminas/laminas-cli/pull/131 to fix CI

**Comment by samsonasik** [comment]
I will rebase when I back to pc

**Comment by samsonasik** [comment]
Rebased 👍

**Review by fezfez — APPROVED** [review]

**Review by gsteel — APPROVED** [review]
Thanks @samsonasik 👍

**Pull request merged**
